version: "3.9"

services:
  postgres:
    image: postgres:16
    platform: linux/amd64
    container_name: postgres-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
  smart_laundry_backend:
    # build: .
    platform: linux/amd64
    container_name: smart-laundry-backend
    restart: unless-stopped
    image: lyheng/smartlaundry_backend:0.0.1-dev.3
    environment:
      ENV: DEV
      DATABASE_URL: postgresql+asyncpg://smart_laundry:p_JI7F7!|3x>@postgres:5432/smart_laundry
      SECRET_KEY: supersecret

      DB_INIT_STRATEGY: create_all

    ports:
      - "8000:8000"

    depends_on:
      - postgres
volumes:
  postgres_data:
