version: "3.9"
services:
  traefik:
    image: traefik:v3.0
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=lyhengtep168@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
  postgres:
    image: postgres:16
    platform: linux/amd64
    container_name: postgres-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - uploads_data:/app/app/uploads
      - ./init:/docker-entrypoint-initdb.d
  smart_laundry_backend:
    # build: .
    platform: linux/amd64
    container_name: smart-laundry-backend
    restart: unless-stopped
    # image: lyheng/smartlaundry_backend:0.0.1-dev.6
    image: lyheng/smartlaundry_backend:db253692a2bfa008ad8f0eee1718d662c51548c2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`smart-laundry.lyhengtep.com`) && PathPrefix(`/api`) || PathPrefix(`/public/uploads`)"
      - "traefik.http.routers.backend.priority=100"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.https-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.backend.middlewares=https-headers"
    environment:
      ENV: DEV
      DATABASE_URL: postgresql+asyncpg://smart_laundry:p_JI7F7!|3x>@postgres:5432/smart_laundry
      SECRET_KEY: supersecret
      FIREBASE_CREDENTIALS_PATH: /app/msg/firebaseServiceAccount.json
      FIREBASE_PROJECT_ID: smartlaundry-ae5d5
      DB_INIT_STRATEGY: create_all
      AWS_S3_ENDPOINT_URL: https://sqs.ap-southeast-1.amazonaws.com/198170202285/pickup_assignment
      AWS_REGION: ap-southeast-1
      TOPIC_PICKUP_ASSIGNMENT: pickup_assignment
      TOPIC_DELIVERY_ASSIGNMENT: delivery_assignment
    volumes:
      - ./firebaseServiceAccount.json:/app/msg/firebaseServiceAccount.json
    ports:
      - "8000:8000"

    depends_on:
      - postgres
  web: 
    # image: lyheng/smart-laundry-web:0.0.1-dev.5
    image: lyheng/smart-laundry-web:abddfc4e0ac64d6be4ac30c8b00a24012700872c
    platform: linux/amd64
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`smart-laundry.lyhengtep.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.priority=10"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.secure-headers.headers.customresponseheaders.Content-Security-Policy=upgrade-insecure-requests"
      - "traefik.http.routers.frontend.middlewares=secure-headers"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_PUBLIC_API_BASE_URL: http://ec2-13-229-201-188.ap-southeast-1.compute.amazonaws.com:8000/api/v1
    restart: unless-stopped

  # localstack:
  #   image: localstack/localstack-pro
  #   ports:
  #     - 4566:4566
  #     - 4510-4559:4510-4559
  #     - 443:443
  #   environment:
  #     - LOCALSTACK_AUTH_TOKEN=ls-gIsaCIcE-detE-gefo-6308-caVi97743e76
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
volumes:
  postgres_data:
  uploads_data: 
