"""create shop_reviews table

Revision ID: 018485bb920e
Revises: l4m5n6o7p8q9
Create Date: 2026-04-27 11:58:56.352737
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '018485bb920e'
down_revision = 'l4m5n6o7p8q9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
