"""remove order_id from shop_reviews add unique per customer per business

Revision ID: 06242c8f4d82
Revises: 018485bb920e
Create Date: 2026-04-27 14:11:53.563736
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '06242c8f4d82'
down_revision = '018485bb920e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_shop_review_order'), 'shop_reviews', type_='unique')
    op.create_unique_constraint('uq_shop_review_per_customer', 'shop_reviews', ['business_id', 'customer_id'])
    op.drop_constraint(op.f('shop_reviews_order_id_fkey'), 'shop_reviews', type_='foreignkey')
    op.drop_column('shop_reviews', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_reviews', sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('shop_reviews_order_id_fkey'), 'shop_reviews', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_shop_review_per_customer', 'shop_reviews', type_='unique')
    op.create_unique_constraint(op.f('uq_shop_review_order'), 'shop_reviews', ['order_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
