"""add order lat lng

Revision ID: 5969d14b0dac
Revises: b9a91db121fe
Create Date: 2026-03-15 19:13:13.433336
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '5969d14b0dac'
down_revision = 'b9a91db121fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('pickup_latitude', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('pickup_longitude', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('delivery_latitude', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('delivery_longitude', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_longitude')
    op.drop_column('orders', 'delivery_latitude')
    op.drop_column('orders', 'pickup_longitude')
    op.drop_column('orders', 'pickup_latitude')
    # ### end Alembic commands ###
