"""add_user_id_to_notifications

Revision ID: 8e3022903015
Revises: 06242c8f4d82
Create Date: 2026-05-02 01:18:59.079336
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '8e3022903015'
down_revision = '06242c8f4d82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_column('notifications', 'user_id')
    # ### end Alembic commands ###
