name: Docker Build
on: 
  push: 
    branches: 
      - dev

jobs:
  docker: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: testing
        run: echo "Testing..."
