name: Docker Build
on: 
  push: 
    branches: 
      - dev

jobs:
  docker: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Docker Image
        run: docker build -t lyheng/smartlaundry_backend:0.0.1-dev.6 .
